[package]
name = "fuzzy_finder"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
regex = "1"
crossterm = "0.27" # For terminal input
rayon = "1.8"      # For parallel traversal (optional but improves speed)
dirs = "6.0.0"
ratatui = "0.26"
